#server:
#  port: 8001
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.dynamic.datasource.entity  # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
#
#spring:
#  application:
#    name: dynamic-datasource
#  datasource:
#    sql-script-encoding: utf-8
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/cloudDB01?useSSL=false&useUnicode=true&characterEncoding=UTF8
#    druid:
#      initial-size: 5
#      max-active: 40
#      min-idle: 5
#      max-wait: 60000
#      validation-query: SELECT 1
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      time-between-eviction-runs-millis: 60000
#      remove-abandoned: true
#      removeAbandonedTimeout: 1800
#      log-abandoned: true
#      filters: stat
#      name: druid-datasource
#

app:
  id: dynamic-datasource
apollo:
  meta: http://192.168.10.175:8060
